"""
Creative asset generation module
===============================

The :mod:`creative_generator` module provides a framework for generating
and selecting advertising creatives (text headlines, descriptions, and
display ad copy) using a large language model.  It encapsulates the
prompt construction, call to an external generative API, post‑processing
filters to ensure compliance with advertising policies, and selection of
high‑quality assets.

This module does not directly call any external APIs; instead, it
defines method stubs that a developer can fill in with actual API
invocation logic (e.g., calling OpenAI's GPT, Anthropic's Claude, etc.).
It includes a simple rules‑based filter for prohibited phrases (derived
from advertising policies【19109617805451†L89-L135】【85214341973367†L94-L121】) and a scoring function
that uses historical performance data to rank generated assets.

Example usage::

    generator = CreativeGenerator()
    prompts = generator.build_prompts(service_name="idlookup.ai")
    raw_ads = generator.generate_raw_creatives(prompts)
    filtered = generator.filter_creatives(raw_ads)
    selected = generator.select_top_creatives(filtered, historical_metrics)

"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Dict, Any, Iterable


@dataclass
class Creative:
    """Represents a single creative asset produced by the generator.

    Attributes:
        headline: The headline text (<= 30 characters for search ads).
        description: The description text (<= 90 characters).
        score: Optional score assigned by the selection algorithm.
    """

    headline: str
    description: str
    score: float | None = None


class CreativeGenerator:
    """Generator for ad creatives using language model prompts.

    The generator is designed to be subclassed or extended to support
    different generative APIs.  It provides methods to build prompts,
    send them to a language model, filter the results, and select the
    top creatives based on historical performance.  It also exposes a
    simple set of prohibited phrases that are removed from the output.
    """

    def __init__(self, prohibited_phrases: Iterable[str] | None = None) -> None:
        # Use a basic list of banned phrases; this can be extended from
        # the policies cited in the specification.  The list below is
        # illustrative and should be replaced with a comprehensive set.
        default_phrases = [
            "violence",
            "harassment",
            "discrimination",
            "illegal",
        ]
        self.prohibited_phrases = set(prohibited_phrases or default_phrases)

    def build_prompts(self, service_name: str) -> str:
        """Construct a prompt for the language model.

        Args:
            service_name: Name of the subscription service being advertised.

        Returns:
            A string containing a well‑structured prompt instructing the
            language model to generate multiple headlines and descriptions.
        """
        # Provide clear instructions and constraints (character limits, tone)
        return (
            "Write five Google Ads headlines (max 30 characters) and four "
            "descriptions (max 90 characters) for a subscription service "
            f"named {service_name}. Emphasize privacy, digital footprint "
            "management, and a clear call to action. Avoid words implying "
            "harassment, discrimination, or illegal activity."
        )

    def generate_raw_creatives(self, prompt: str) -> List[Creative]:
        """Generate raw creatives via a language model API.

        This method is a placeholder that should be replaced with a call to
        an external generative model (e.g., through OpenAI's API).  For
        demonstration purposes, it returns an empty list.

        Args:
            prompt: Prompt string generated by :meth:`build_prompts`.

        Returns:
            A list of :class:`Creative` objects containing headline and
            description pairs.  The default implementation returns an
            empty list; developers should override this method.
        """
        # TODO: Implement call to generative model and parse outputs
        return []

    def filter_creatives(self, creatives: Iterable[Creative]) -> List[Creative]:
        """Filter out creatives containing prohibited phrases.

        Args:
            creatives: Iterable of :class:`Creative` objects produced by
                :meth:`generate_raw_creatives`.

        Returns:
            A list of creatives that do not contain any banned phrases.
        """
        filtered: List[Creative] = []
        for creative in creatives:
            text = (creative.headline + " " + creative.description).lower()
            if any(p in text for p in self.prohibited_phrases):
                continue
            filtered.append(creative)
        return filtered

    def select_top_creatives(
        self,
        creatives: Iterable[Creative],
        performance_history: Dict[str, float] | None = None,
        top_n: int = 5,
    ) -> List[Creative]:
        """Select top creatives based on historical performance scores.

        Args:
            creatives: Iterable of filtered :class:`Creative` objects.
            performance_history: Optional mapping of creative text (e.g.,
                headline + description) to a historical performance score.
            top_n: Number of top creatives to select.

        Returns:
            List of the highest‑scoring creatives, each annotated with a
            ``score`` attribute.  If no historical data is provided, the
            selection is random (here implemented as original order).
        """
        # Assign scores from history or default to zero
        scored: List[Creative] = []
        for creative in creatives:
            key = creative.headline + "|" + creative.description
            score = 0.0
            if performance_history and key in performance_history:
                score = performance_history[key]
            creative.score = score
            scored.append(creative)
        # Sort by score descending
        scored.sort(key=lambda c: c.score or 0.0, reverse=True)
        return scored[:top_n]